---
- hosts: api-service-server
  become: true

  tasks:
  - name: Copy Api Service Files
    copy:
      src: ./main
      dest: /opt/brandon/kong-service/
      owner: root
      group: root
      mode: 0640

  - name: Start Api
    shell: cd /opt/brandon/kong-service; ./main &